version: "3"
services:
  db:
    image: postgres:15.1
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    env_file:
    - .env
  backend:
    image: node:18
    volumes:
      - ./backend:/usr/local/app:ro
      - ./schema/post.graphql:/usr/local/schema/post.graphql:ro
    env_file:
    - .env
    working_dir: /usr/local/app
    ports:
      - "8080:8080"
    command:
      ["npx", "nodemon"]
